const http = require('http');
const fs = require('fs');
const fsp = fs.promises;
const path = require('path');
const crypto = require('crypto');
const { URL } = require('url');

const PORT = Number(process.env.PORT || 3000);
const HOST = process.env.HOST || '0.0.0.0';
const DATA_DIR = path.resolve(process.env.DATA_DIR || process.env.RAILWAY_VOLUME_MOUNT_PATH || path.join(__dirname, 'data'));
const PUBLIC_DIR = path.join(__dirname, 'public');
const DEFAULT_ADMIN_USERNAME = process.env.ADMIN_USERNAME || 'admin';
const DEFAULT_ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'Admin12345';
const DEFAULT_SYSTEM_PASSWORD = process.env.SYSTEM_PASSWORD || 'System12345';
const SEED_DEMO = String(process.env.SEED_DEMO || 'true').toLowerCase() !== 'false';
const SHOW_DEMO_CREDENTIALS = String(process.env.SHOW_DEMO_CREDENTIALS || 'false').toLowerCase() === 'true';
const SESSION_TTL_MS = Number(process.env.SESSION_TTL_HOURS || 12) * 60 * 60 * 1000;
const MAX_BODY_BYTES = 8 * 1024 * 1024;

const dirs = {
  admins: path.join(DATA_DIR, 'admins'),
  teachers: path.join(DATA_DIR, 'teachers'),
  students: path.join(DATA_DIR, 'students'),
  groups: path.join(DATA_DIR, 'groups'),
  attendance: path.join(DATA_DIR, 'attendance'),
  settings: path.join(DATA_DIR, 'settings')
};
const sessions = new Map();

function nowISO(){ return new Date().toISOString(); }
function makeId(prefix){ return `${prefix}_${crypto.randomBytes(4).toString('hex')}_${Date.now().toString(36)}`; }
function normalize(v, max=120){ return String(v||'').trim().slice(0,max); }
function safeEntityId(value){ const t=String(value||'').trim(); if(!/^[a-zA-Z0-9_-]{1,80}$/.test(t)){ const e=new Error('ID formati noto‘g‘ri'); e.statusCode=400; throw e;} return t; }
function entityFile(type, entityId){ if(!dirs[type]) throw new Error('Unknown entity type'); const file=path.resolve(dirs[type], `${safeEntityId(entityId)}.json`); const base=path.resolve(dirs[type]); if(!file.startsWith(base+path.sep)){ const e=new Error('Fayl yo‘li xavfsiz emas'); e.statusCode=400; throw e;} return file; }
function hashPassword(password){ const salt=crypto.randomBytes(16).toString('hex'); const hash=crypto.createHash('sha256').update(`${salt}:${String(password||'')}`).digest('hex'); return `sha256$${salt}$${hash}`; }
function comparePassword(password, stored){ const s=String(stored||''); if(s.startsWith('sha256$')){ const [,salt,hash]=s.split('$'); const check=crypto.createHash('sha256').update(`${salt}:${String(password||'')}`).digest('hex'); return crypto.timingSafeEqual(Buffer.from(hash), Buffer.from(check)); } return String(password||'') === s; }
function cleanUser(user){ if(!user) return null; const { passwordHash, ...safe } = user; return safe; }
function assertPassword(password, label='Parol'){ if(String(password||'').length < 5){ const e=new Error(`${label} kamida 5 ta belgidan iborat bo‘lsin`); e.statusCode=400; throw e;} }
function validateRequired(body, fields){ for(const field of fields){ if(!String(body[field]||'').trim()){ const e=new Error(`${field} kiritilishi kerak`); e.statusCode=400; throw e; } } }
function safeIdArray(value){ if(!Array.isArray(value)) return []; return [...new Set(value.map(x=>safeEntityId(x)))]; }
function validateDate(date){ const value=String(date||''); if(!/^\d{4}-\d{2}-\d{2}$/.test(value)){ const e=new Error('Sana YYYY-MM-DD formatda bo‘lishi kerak'); e.statusCode=400; throw e; } const parsed=new Date(`${value}T00:00:00.000Z`); if(Number.isNaN(parsed.getTime()) || parsed.toISOString().slice(0,10)!==value){ const e=new Error('Sana haqiqiy bo‘lishi kerak'); e.statusCode=400; throw e; } }
function sortDates(dates){ return [...new Set(dates||[])].sort((a,b)=>a.localeCompare(b)); }

async function ensureDir(dir){ await fsp.mkdir(dir,{recursive:true}); }
async function fileExists(file){ try{ await fsp.access(file); return true;}catch{return false;} }
async function readJSON(file, fallback=null){ try{ return JSON.parse(await fsp.readFile(file,'utf8')); }catch{return fallback;} }
async function writeJSON(file, value){ await ensureDir(path.dirname(file)); await fsp.writeFile(file, JSON.stringify(value,null,2),'utf8'); }
async function listJSON(dir){ await ensureDir(dir); const files=(await fsp.readdir(dir)).filter(f=>f.endsWith('.json')); const rows=[]; for(const f of files){ const item=await readJSON(path.join(dir,f)); if(item) rows.push(item); } return rows; }
async function deleteFileIfExists(file){ try{ await fsp.unlink(file); }catch{} }

async function getAllData(){ const [admins,teachers,students,groups,attendance,settings]=await Promise.all([listJSON(dirs.admins),listJSON(dirs.teachers),listJSON(dirs.students),listJSON(dirs.groups),listJSON(dirs.attendance),readJSON(path.join(dirs.settings,'system.json'),{})]); return {admins,teachers,students,groups,attendance,settings}; }
async function getPublicState(user){ const all=await getAllData(); const admins=all.admins.map(cleanUser), teachers=all.teachers.map(cleanUser), students=all.students.map(cleanUser), groups=all.groups, attendance=all.attendance; if(user.role==='admin') return {me:cleanUser(user), admins, teachers, students, groups, attendance}; if(user.role==='teacher'){ const myGroups=groups.filter(g=>(g.teacherIds||[]).includes(user.id)); const studentIds=new Set(myGroups.flatMap(g=>g.studentIds||[])); return {me:cleanUser(user), admins:[], teachers:[cleanUser(user)], students:students.filter(s=>studentIds.has(s.id)), groups:myGroups, attendance:attendance.filter(a=>myGroups.some(g=>g.id===a.groupId))}; } const myGroups=groups.filter(g=>(g.studentIds||[]).includes(user.id)); return {me:cleanUser(user), admins:[], teachers:teachers.filter(t=>myGroups.some(g=>(g.teacherIds||[]).includes(t.id))), students:[cleanUser(user)], groups:myGroups, attendance:attendance.filter(a=>myGroups.some(g=>g.id===a.groupId))}; }
async function findUserByUsername(username){ const n=String(username||'').trim().toLowerCase(); const all=await getAllData(); return [...all.admins,...all.teachers,...all.students].find(u=>String(u.username||'').trim().toLowerCase()===n) || null; }
async function findUserById(userId){ const all=await getAllData(); return [...all.admins,...all.teachers,...all.students].find(u=>u.id===userId) || null; }
async function ensureUniqueUsername(username, exceptId=''){ const u=await findUserByUsername(username); if(u && u.id!==exceptId){ const e=new Error('Bu username allaqachon band'); e.statusCode=409; throw e; } }
async function removeFromGroups(type, entityId){ const groups=await listJSON(dirs.groups); for(const g of groups){ if(type==='teacher') g.teacherIds=(g.teacherIds||[]).filter(id=>id!==entityId); if(type==='student') g.studentIds=(g.studentIds||[]).filter(id=>id!==entityId); g.updatedAt=nowISO(); await writeJSON(entityFile('groups',g.id),g); } }
async function verifyEntityAccess(req, type, entityId){ const item=await readJSON(entityFile(type,entityId)); if(!item){ const e=new Error('Ma’lumot topilmadi'); e.statusCode=404; throw e; } if(req.user.role!=='admin'){ const e=new Error('Ruxsat yo‘q'); e.statusCode=403; throw e; } return item; }
function canAccessGroup(user, group){ if(!group) return false; if(user.role==='admin') return true; if(user.role==='teacher') return (group.teacherIds||[]).includes(user.id); if(user.role==='student') return (group.studentIds||[]).includes(user.id); return false; }

async function seedFreshData({withDemo=true}={}){ for(const d of Object.values(dirs)) await ensureDir(d); const adminId='admin_main'; await writeJSON(entityFile('admins',adminId),{id:adminId,role:'admin',firstName:process.env.ADMIN_FIRST_NAME||'Smart',lastName:process.env.ADMIN_LAST_NAME||'Admin',username:DEFAULT_ADMIN_USERNAME,passwordHash:hashPassword(DEFAULT_ADMIN_PASSWORD),phone:process.env.ADMIN_PHONE||'+998 90 000 00 00',createdAt:nowISO(),updatedAt:nowISO()}); await writeJSON(path.join(dirs.settings,'system.json'),{systemPasswordHash:hashPassword(DEFAULT_SYSTEM_PASSWORD),defaultSystemPasswordHint:'ENV orqali berilgan',updatedAt:nowISO()}); if(!withDemo) return; const teacherId='teacher_demo_1', student1='student_demo_1', student2='student_demo_2', student3='student_demo_3', groupId='group_demo_1', today=new Date().toISOString().slice(0,10); await writeJSON(entityFile('teachers',teacherId),{id:teacherId,role:'teacher',firstName:'Azizbek',lastName:'Karimov',username:'ustoz1',passwordHash:hashPassword('12345'),phone:'+998 90 123 45 67',createdAt:nowISO(),updatedAt:nowISO()}); for(const [sid,fn,ln,un,ph] of [[student1,'Jasur','Aliyev','jasur','+998 91 111 22 33'],[student2,'Madina','Sobirova','madina','+998 93 222 33 44'],[student3,'Aziza','Tursunova','aziza','+998 94 333 44 55']]) await writeJSON(entityFile('students',sid),{id:sid,role:'student',firstName:fn,lastName:ln,username:un,passwordHash:hashPassword('12345'),phone:ph,groupId,createdAt:nowISO(),updatedAt:nowISO()}); await writeJSON(entityFile('groups',groupId),{id:groupId,name:'IELTS Foundation A1',teacherIds:[teacherId],studentIds:[student1,student2,student3],createdAt:nowISO(),updatedAt:nowISO()}); await writeJSON(entityFile('attendance',groupId),{groupId,dates:[today],records:{[student1]:{[today]:{status:'present',note:'',updatedAt:nowISO(),by:'seed'}},[student2]:{[today]:{status:'absent',note:'Xabar berilmagan',updatedAt:nowISO(),by:'seed'}},[student3]:{[today]:{status:'excused',note:'Oilaviy sabab',updatedAt:nowISO(),by:'seed'}}},createdAt:nowISO(),updatedAt:nowISO()}); }
async function initData(){ await ensureDir(DATA_DIR); for(const d of Object.values(dirs)) await ensureDir(d); const adminFiles=(await fsp.readdir(dirs.admins)).filter(f=>f.endsWith('.json')); if(adminFiles.length===0) await seedFreshData({withDemo:SEED_DEMO}); if(!(await fileExists(path.join(dirs.settings,'system.json')))) await writeJSON(path.join(dirs.settings,'system.json'),{systemPasswordHash:hashPassword(DEFAULT_SYSTEM_PASSWORD),defaultSystemPasswordHint:'ENV orqali berilgan',updatedAt:nowISO()}); }

function send(res, status, body, headers={}){ const payload=typeof body==='string'||Buffer.isBuffer(body)?body:JSON.stringify(body); res.writeHead(status, {'Content-Type': Buffer.isBuffer(body)?'application/octet-stream':(typeof body==='string'? 'text/plain; charset=utf-8':'application/json; charset=utf-8'), ...headers}); res.end(payload); }
function json(res, body, status=200){ send(res,status,body,{'Content-Type':'application/json; charset=utf-8'}); }
function error(res, err){ console.error(err); json(res,{error:err.message||'Server xatosi'}, err.statusCode||500); }
async function readBody(req){ return new Promise((resolve,reject)=>{ const chunks=[]; let size=0; req.on('data',c=>{ size+=c.length; if(size>MAX_BODY_BYTES){ reject(Object.assign(new Error('Fayl yoki so‘rov hajmi juda katta'),{statusCode:413})); req.destroy(); } else chunks.push(c); }); req.on('end',()=>resolve(Buffer.concat(chunks))); req.on('error',reject); }); }
async function getJsonBody(req){ const buf=await readBody(req); if(!buf.length) return {}; try{return JSON.parse(buf.toString('utf8'));}catch{ const e=new Error('JSON noto‘g‘ri'); e.statusCode=400; throw e; } }
function extractMultipartText(buffer, boundary, field){ const raw=buffer.toString('latin1'); const marker=`name="${field}"`; const idx=raw.indexOf(marker); if(idx<0) return ''; const start=raw.indexOf('\r\n\r\n', idx); if(start<0) return ''; const end=raw.indexOf(`\r\n--${boundary}`, start+4); return Buffer.from(raw.slice(start+4,end), 'latin1').toString('utf8').trim(); }
function extractMultipartFileText(buffer, boundary, field){ const raw=buffer.toString('latin1'); const marker=`name="${field}"`; const idx=raw.indexOf(marker); if(idx<0) return ''; const start=raw.indexOf('\r\n\r\n', idx); if(start<0) return ''; const end=raw.indexOf(`\r\n--${boundary}`, start+4); return Buffer.from(raw.slice(start+4,end), 'latin1').toString('utf8'); }
function pruneExpired(){ const cutoff=Date.now()-SESSION_TTL_MS; for(const [k,s] of sessions.entries()) if(!s.createdAtMs || s.createdAtMs<cutoff) sessions.delete(k); }
async function getAuthed(req){ pruneExpired(); const h=req.headers.authorization||''; const token=h.startsWith('Bearer ')?h.slice(7):''; const session=token?sessions.get(token):null; if(!session){ const e=new Error('Avval tizimga kiring'); e.statusCode=401; throw e; } const user=await findUserById(session.userId); if(!user){ const e=new Error('Foydalanuvchi topilmadi'); e.statusCode=401; throw e; } req.session=session; req.user=user; req.userId=user.id; return user; }
function requireAdmin(req){ if(req.user.role!=='admin'){ const e=new Error('Bu amal faqat admin uchun'); e.statusCode=403; throw e; } }
async function checkSystemPassword(password){ const settings=await readJSON(path.join(dirs.settings,'system.json'),{}); return comparePassword(password, settings.systemPasswordHash); }
async function route(req, res){ const url=new URL(req.url, `http://${req.headers.host||'localhost'}`); const pathname=decodeURIComponent(url.pathname); try{
  if(req.method==='GET' && pathname==='/api/health') return json(res,{ok:true,app:'course-attendance-crm',version:'3.0.0-no-deps',time:nowISO()});
  if(req.method==='GET' && pathname==='/api/public-config') return json(res,{showDemoCredentials:SHOW_DEMO_CREDENTIALS});
  if(req.method==='POST' && pathname==='/api/login'){ const body=await getJsonBody(req); const user=await findUserByUsername(body.username); if(!user || !comparePassword(body.password,user.passwordHash)) return json(res,{error:'Username yoki parol noto‘g‘ri'},401); const token=crypto.randomBytes(32).toString('hex'); sessions.set(token,{token,userId:user.id,createdAt:nowISO(),createdAtMs:Date.now(),lastSeenAt:nowISO()}); return json(res,{token,user:cleanUser(user),state:await getPublicState(user)}); }
  if(pathname.startsWith('/api/')) await getAuthed(req);
  if(req.method==='POST' && pathname==='/api/logout'){ sessions.delete(req.session.token); return json(res,{ok:true}); }
  if(req.method==='GET' && pathname==='/api/state') return json(res, await getPublicState(req.user));
  let m;
  if(req.method==='POST' && pathname==='/api/teachers'){ requireAdmin(req); const body=await getJsonBody(req); validateRequired(body,['firstName','lastName','username','password']); assertPassword(body.password); await ensureUniqueUsername(body.username); const teacher={id:makeId('teacher'),role:'teacher',firstName:normalize(body.firstName),lastName:normalize(body.lastName),username:normalize(body.username,60),passwordHash:hashPassword(body.password),phone:normalize(body.phone,40),createdAt:nowISO(),updatedAt:nowISO()}; await writeJSON(entityFile('teachers',teacher.id),teacher); return json(res,{ok:true,teacher:cleanUser(teacher),state:await getPublicState(req.user)}); }
  if((m=pathname.match(/^\/api\/teachers\/([^/]+)$/))){ requireAdmin(req); const tid=m[1]; if(req.method==='PUT'){ const body=await getJsonBody(req); const teacher=await verifyEntityAccess(req,'teachers',tid); validateRequired(body,['firstName','lastName','username']); await ensureUniqueUsername(body.username,teacher.id); Object.assign(teacher,{firstName:normalize(body.firstName),lastName:normalize(body.lastName),username:normalize(body.username,60),phone:normalize(body.phone,40),updatedAt:nowISO()}); if(String(body.password||'').trim()){ assertPassword(body.password); teacher.passwordHash=hashPassword(body.password); } await writeJSON(entityFile('teachers',teacher.id),teacher); return json(res,{ok:true,teacher:cleanUser(teacher),state:await getPublicState(req.user)}); } if(req.method==='DELETE'){ await verifyEntityAccess(req,'teachers',tid); await removeFromGroups('teacher',tid); await deleteFileIfExists(entityFile('teachers',tid)); return json(res,{ok:true,state:await getPublicState(req.user)}); } }
  if(req.method==='POST' && pathname==='/api/students'){ requireAdmin(req); const body=await getJsonBody(req); validateRequired(body,['firstName','lastName','username','password']); assertPassword(body.password); await ensureUniqueUsername(body.username); const student={id:makeId('student'),role:'student',firstName:normalize(body.firstName),lastName:normalize(body.lastName),username:normalize(body.username,60),passwordHash:hashPassword(body.password),phone:normalize(body.phone,40),groupId:normalize(body.groupId,80),createdAt:nowISO(),updatedAt:nowISO()}; await writeJSON(entityFile('students',student.id),student); if(student.groupId){ const group=await readJSON(entityFile('groups',student.groupId)); if(group){ group.studentIds=[...new Set([...(group.studentIds||[]),student.id])]; group.updatedAt=nowISO(); await writeJSON(entityFile('groups',group.id),group); }} return json(res,{ok:true,student:cleanUser(student),state:await getPublicState(req.user)}); }
  if((m=pathname.match(/^\/api\/students\/([^/]+)$/))){ requireAdmin(req); const sid=m[1]; if(req.method==='PUT'){ const body=await getJsonBody(req); const student=await verifyEntityAccess(req,'students',sid); validateRequired(body,['firstName','lastName','username']); await ensureUniqueUsername(body.username,student.id); const oldGroupId=student.groupId; Object.assign(student,{firstName:normalize(body.firstName),lastName:normalize(body.lastName),username:normalize(body.username,60),phone:normalize(body.phone,40),groupId:normalize(body.groupId,80),updatedAt:nowISO()}); if(String(body.password||'').trim()){ assertPassword(body.password); student.passwordHash=hashPassword(body.password); } await writeJSON(entityFile('students',student.id),student); if(oldGroupId && oldGroupId!==student.groupId){ const old=await readJSON(entityFile('groups',oldGroupId)); if(old){ old.studentIds=(old.studentIds||[]).filter(id=>id!==student.id); old.updatedAt=nowISO(); await writeJSON(entityFile('groups',old.id),old);} } if(student.groupId){ const g=await readJSON(entityFile('groups',student.groupId)); if(g){ g.studentIds=[...new Set([...(g.studentIds||[]),student.id])]; g.updatedAt=nowISO(); await writeJSON(entityFile('groups',g.id),g);} } return json(res,{ok:true,student:cleanUser(student),state:await getPublicState(req.user)}); } if(req.method==='DELETE'){ await verifyEntityAccess(req,'students',sid); await removeFromGroups('student',sid); const attendanceFiles=await listJSON(dirs.attendance); for(const a of attendanceFiles){ if(a.records && a.records[sid]){ delete a.records[sid]; a.updatedAt=nowISO(); await writeJSON(entityFile('attendance',a.groupId),a); }} await deleteFileIfExists(entityFile('students',sid)); return json(res,{ok:true,state:await getPublicState(req.user)}); } }
  if(req.method==='POST' && pathname==='/api/groups'){ requireAdmin(req); const body=await getJsonBody(req); validateRequired(body,['name']); const group={id:makeId('group'),name:normalize(body.name,120),teacherIds:safeIdArray(body.teacherIds),studentIds:safeIdArray(body.studentIds),createdAt:nowISO(),updatedAt:nowISO()}; await writeJSON(entityFile('groups',group.id),group); await writeJSON(entityFile('attendance',group.id),{groupId:group.id,dates:[],records:{},createdAt:nowISO(),updatedAt:nowISO()}); const students=await listJSON(dirs.students); for(const s of students){ if(group.studentIds.includes(s.id)){ s.groupId=group.id; s.updatedAt=nowISO(); await writeJSON(entityFile('students',s.id),s); }} return json(res,{ok:true,group,state:await getPublicState(req.user)}); }
  if((m=pathname.match(/^\/api\/groups\/([^/]+)$/))){ const gid=m[1]; if(req.method==='PUT'){ requireAdmin(req); const body=await getJsonBody(req); const group=await verifyEntityAccess(req,'groups',gid); validateRequired(body,['name']); const oldStudentIds=new Set(group.studentIds||[]); group.name=normalize(body.name,120); group.teacherIds=safeIdArray(body.teacherIds); group.studentIds=safeIdArray(body.studentIds); group.updatedAt=nowISO(); await writeJSON(entityFile('groups',group.id),group); const students=await listJSON(dirs.students); for(const s of students){ const should=group.studentIds.includes(s.id), was=oldStudentIds.has(s.id); if(should||was){ s.groupId=should?group.id:''; s.updatedAt=nowISO(); await writeJSON(entityFile('students',s.id),s); }} return json(res,{ok:true,group,state:await getPublicState(req.user)}); } if(req.method==='DELETE'){ requireAdmin(req); await verifyEntityAccess(req,'groups',gid); const students=await listJSON(dirs.students); for(const s of students){ if(s.groupId===gid){ s.groupId=''; s.updatedAt=nowISO(); await writeJSON(entityFile('students',s.id),s); }} await deleteFileIfExists(entityFile('groups',gid)); await deleteFileIfExists(entityFile('attendance',gid)); return json(res,{ok:true,state:await getPublicState(req.user)}); } }
  if((m=pathname.match(/^\/api\/groups\/([^/]+)\/dates$/)) && req.method==='POST'){ const group=await readJSON(entityFile('groups',m[1])); if(!canAccessGroup(req.user,group)||req.user.role==='student') return json(res,{error:'Bu guruhga ruxsat yo‘q'},403); const body=await getJsonBody(req); const date=String(body.date||'').trim(); validateDate(date); let attendance=await readJSON(entityFile('attendance',group.id)); if(!attendance) attendance={groupId:group.id,dates:[],records:{},createdAt:nowISO()}; attendance.dates=sortDates([...(attendance.dates||[]),date]); attendance.updatedAt=nowISO(); await writeJSON(entityFile('attendance',group.id),attendance); return json(res,{ok:true,attendance,state:await getPublicState(req.user)}); }
  if((m=pathname.match(/^\/api\/groups\/([^/]+)\/dates\/(\d{4}-\d{2}-\d{2})$/)) && req.method==='DELETE'){ const group=await readJSON(entityFile('groups',m[1])); if(!canAccessGroup(req.user,group)||req.user.role==='student') return json(res,{error:'Bu guruhga ruxsat yo‘q'},403); validateDate(m[2]); const attendance=await readJSON(entityFile('attendance',group.id),{groupId:group.id,dates:[],records:{}}); attendance.dates=(attendance.dates||[]).filter(d=>d!==m[2]); for(const sid of Object.keys(attendance.records||{})) if(attendance.records[sid]) delete attendance.records[sid][m[2]]; attendance.updatedAt=nowISO(); await writeJSON(entityFile('attendance',group.id),attendance); return json(res,{ok:true,state:await getPublicState(req.user)}); }
  if(req.method==='PUT' && pathname==='/api/attendance'){ const body=await getJsonBody(req); const {groupId,studentId,date}=body; const status=String(body.status||'').trim(), note=String(body.note||'').trim(); validateDate(date); if(!['','present','absent','late','excused'].includes(status)) return json(res,{error:'Status noto‘g‘ri'},400); const group=await readJSON(entityFile('groups',groupId)); if(!canAccessGroup(req.user,group)||req.user.role==='student') return json(res,{error:'Bu guruhga ruxsat yo‘q'},403); if(!(group.studentIds||[]).includes(studentId)) return json(res,{error:'O‘quvchi bu guruhda emas'},400); let attendance=await readJSON(entityFile('attendance',groupId)); if(!attendance) attendance={groupId,dates:[],records:{},createdAt:nowISO()}; attendance.dates=sortDates([...(attendance.dates||[]),date]); attendance.records=attendance.records||{}; attendance.records[studentId]=attendance.records[studentId]||{}; if(!status) delete attendance.records[studentId][date]; else attendance.records[studentId][date]={status,note,updatedAt:nowISO(),by:req.user.id}; attendance.updatedAt=nowISO(); await writeJSON(entityFile('attendance',groupId),attendance); return json(res,{ok:true,attendance,state:await getPublicState(req.user)}); }
  if(req.method==='POST' && pathname==='/api/system/verify'){ requireAdmin(req); const body=await getJsonBody(req); if(!(await checkSystemPassword(body.systemPassword))) return json(res,{error:'Maxfiy system parol noto‘g‘ri'},403); return json(res,{ok:true}); }
  if(req.method==='POST' && pathname==='/api/system/change-password'){ requireAdmin(req); const body=await getJsonBody(req); if(!(await checkSystemPassword(body.systemPassword))) return json(res,{error:'Maxfiy system parol noto‘g‘ri'},403); assertPassword(body.newPassword,'Yangi system parol'); const settings=await readJSON(path.join(dirs.settings,'system.json'),{}); settings.systemPasswordHash=hashPassword(body.newPassword); settings.defaultSystemPasswordHint='O‘zgartirilgan'; settings.updatedAt=nowISO(); await writeJSON(path.join(dirs.settings,'system.json'),settings); return json(res,{ok:true}); }
  if(req.method==='GET' && pathname==='/api/system/backup.zip'){ requireAdmin(req); const password=url.searchParams.get('systemPassword') || req.headers['x-system-password']; if(!(await checkSystemPassword(password))) return json(res,{error:'Maxfiy system parol noto‘g‘ri'},403); const data=await getAllData(); const backup={exportedAt:nowISO(),app:'course-attendance-crm',version:'3.0.0-no-deps',data}; const buf=Buffer.from(JSON.stringify(backup,null,2),'utf8'); res.writeHead(200,{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename="course-attendance-backup-${new Date().toISOString().slice(0,10)}.zip"`}); return res.end(buf); }
  if(req.method==='POST' && pathname==='/api/system/restore'){ requireAdmin(req); const ctype=req.headers['content-type']||''; const boundary=(ctype.match(/boundary=(.+)$/)||[])[1]; const buf=await readBody(req); const password=boundary?extractMultipartText(buf,boundary,'systemPassword'):''; if(!(await checkSystemPassword(password))) return json(res,{error:'Maxfiy system parol noto‘g‘ri'},403); const fileText=boundary?extractMultipartFileText(buf,boundary,'backup'):''; let parsed; try{ parsed=JSON.parse(fileText); }catch{ return json(res,{error:'Bu versiyada faqat ushbu tizimdan olingan backup fayl tiklanadi'},400); } if(!parsed.data) return json(res,{error:'Backup formati noto‘g‘ri'},400); await fsp.rm(DATA_DIR,{recursive:true,force:true}); for(const d of Object.values(dirs)) await ensureDir(d); for(const item of parsed.data.admins||[]) await writeJSON(entityFile('admins',item.id),item); for(const item of parsed.data.teachers||[]) await writeJSON(entityFile('teachers',item.id),item); for(const item of parsed.data.students||[]) await writeJSON(entityFile('students',item.id),item); for(const item of parsed.data.groups||[]) await writeJSON(entityFile('groups',item.id),item); for(const item of parsed.data.attendance||[]) await writeJSON(entityFile('attendance',item.groupId),item); await writeJSON(path.join(dirs.settings,'system.json'),parsed.data.settings||{systemPasswordHash:hashPassword(DEFAULT_SYSTEM_PASSWORD),updatedAt:nowISO()}); sessions.clear(); return json(res,{ok:true,message:'Backup qayta tiklandi. Qayta login qiling.'}); }
  if(req.method==='POST' && pathname==='/api/system/wipe'){ requireAdmin(req); const body=await getJsonBody(req); if(!(await checkSystemPassword(body.systemPassword))) return json(res,{error:'Maxfiy system parol noto‘g‘ri'},403); await fsp.rm(DATA_DIR,{recursive:true,force:true}); await seedFreshData({withDemo:false}); sessions.clear(); return json(res,{ok:true,message:`Barcha ma’lumotlar o‘chirildi. Admin login qayta yaratildi: ${DEFAULT_ADMIN_USERNAME}`}); }
  if(pathname.startsWith('/api/')) return json(res,{error:'API topilmadi'},404);
  await serveStatic(pathname,res);
}catch(err){ error(res,err); }}

async function serveStatic(pathname,res){ let file=pathname==='/'?path.join(PUBLIC_DIR,'index.html'):path.join(PUBLIC_DIR,pathname); file=path.resolve(file); if(!file.startsWith(path.resolve(PUBLIC_DIR)+path.sep) && file!==path.join(PUBLIC_DIR,'index.html')) file=path.join(PUBLIC_DIR,'index.html'); if(!(await fileExists(file))) file=path.join(PUBLIC_DIR,'index.html'); const ext=path.extname(file).toLowerCase(); const types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml'}; const data=await fsp.readFile(file); res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY'}); res.end(data); }

initData().then(()=>{ http.createServer(route).listen(PORT, HOST, ()=>{ console.log(`Course attendance CRM running on ${HOST}:${PORT}`); console.log(`Data directory: ${DATA_DIR}`); }); }).catch(err=>{ console.error('Startup error:',err); process.exit(1); });
